name: x86 defconfig

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run:  |
        sudo apt update
        sudo apt install \
            make gcc flex bison gzip \
            gettext imagemagick u-boot-tools
    - name: make x86_defconfig
      run:  make x86_defconfig
    - name: make
      run:  make
    - name: make distclean
      run:  make distclean
